import torch, torch.nn as nn
class CrossSpeciesResidualPredictor(nn.Module):
    def __init__(self,n_genes,n_perturbations,atac_dim=256,perturb_dim=128,hidden_dim=512,rank=64,dropout=0.1,residual_scale=0.01,use_atac=True,learn_alpha=True,alpha_init=-1.0,alpha_min=-3.0,alpha_max=1.0):
        super().__init__(); self.use_atac=use_atac; self.residual_scale=residual_scale; self.learn_alpha=learn_alpha; self.alpha_min=alpha_min; self.alpha_max=alpha_max
        self.perturb_emb=nn.Embedding(n_perturbations,perturb_dim); self.control_encoder=nn.Sequential(nn.Linear(n_genes,hidden_dim),nn.LayerNorm(hidden_dim),nn.SiLU(),nn.Dropout(dropout),nn.Linear(hidden_dim,perturb_dim),nn.LayerNorm(perturb_dim)); self.source_delta_encoder=nn.Sequential(nn.Linear(n_genes,hidden_dim),nn.LayerNorm(hidden_dim),nn.SiLU(),nn.Dropout(dropout),nn.Linear(hidden_dim,perturb_dim),nn.LayerNorm(perturb_dim)); self.atac_encoder=nn.Sequential(nn.Linear(atac_dim,hidden_dim),nn.LayerNorm(hidden_dim),nn.SiLU(),nn.Dropout(dropout),nn.Linear(hidden_dim,perturb_dim),nn.LayerNorm(perturb_dim)) if use_atac else None
        self.fusion=nn.Sequential(nn.Linear(perturb_dim*4,hidden_dim),nn.LayerNorm(hidden_dim),nn.SiLU(),nn.Dropout(dropout),nn.Linear(hidden_dim,hidden_dim),nn.LayerNorm(hidden_dim),nn.SiLU()); self.coeff_head=nn.Linear(hidden_dim,rank); self.gene_basis=nn.Parameter(torch.randn(rank,n_genes)*0.01); self.gate_head=nn.Sequential(nn.Linear(hidden_dim,n_genes),nn.Sigmoid())
        self.alpha_head=nn.Linear(hidden_dim,1) if learn_alpha else None; self.register_buffer('fixed_alpha',torch.tensor(float(alpha_init))); nn.init.zeros_(self.coeff_head.weight); nn.init.zeros_(self.coeff_head.bias)
    def compute_alpha(self,h):
        if not self.learn_alpha: return self.fixed_alpha.view(1,1).expand(h.shape[0],1)
        s=torch.sigmoid(self.alpha_head(h)); return self.alpha_min+(self.alpha_max-self.alpha_min)*s
    def forward(self,control,source_delta,perturb_id,atac_feat=None,alpha_override=None,return_details=False):
        zc=self.control_encoder(control); zs=self.source_delta_encoder(source_delta); zp=self.perturb_emb(perturb_id); za=self.atac_encoder(atac_feat) if (self.use_atac and atac_feat is not None) else torch.zeros_like(zc); h=self.fusion(torch.cat([zc,zs,zp,za],dim=1)); residual=self.residual_scale*self.gate_head(h)*(self.coeff_head(h)@self.gene_basis); alpha=self.compute_alpha(h) if alpha_override is None else (torch.full((control.shape[0],1),float(alpha_override),device=control.device) if not torch.is_tensor(alpha_override) else alpha_override.view(-1,1).to(control.device)); pred_delta=source_delta+alpha*residual; pred=control+pred_delta
        return pred if not return_details else {"pred":pred,"pred_delta":pred_delta,"source_delta":source_delta,"residual":residual,"alpha":alpha}
